version = 1

test_patterns = ["/test/*.spec.js"]

exclude_patterns = ["/dist/*.min.js"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]